---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - api.0jk6.github.io
  resources:
  - conjurs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - api.0jk6.github.io
  resources:
  - conjurs/finalizers
  verbs:
  - update
- apiGroups:
  - api.0jk6.github.io
  resources:
  - conjurs/status
  verbs:
  - get
  - patch
  - update
